name: Maven Build and Archive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      GIT_REPO: rajadevops2025/mavendemo
      GIT_BRANCH: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GIT_REPO }}
          ref: ${{ env.GIT_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: maven-build-artifacts
          path: target/*.jar
